Add input block
VladimirTatarintsev/admin-panel-makeup pull request #3
Opened 2022-01-28 17:37 UTC by VladimirTatarintsev

Prettier ИМХО ужасно форматнул ui-kit.html

2022-01-29 18:32 UTC, Muslik requested changes
Прикрепил видео

2022-01-30 19:14 UTC, VladimirTatarintsev commented
Ссылка на сайт   https://vladimirtatarintsev.github.io/admin-panel-makeup/

2022-02-01 22:13 UTC, Muslik approved these changes
Пара замечаний. Исправьте перед тем как мержить

2022-02-01 22:13 UTC, Muslik commented on blocks/input.css
> +  height: 72px;
вот эта высота, а также выше и ниже лишняя. Не нужно жестко задавать ее. Пусть сам контент решит сколько ему нужно. Также не нужно делать столько классов только чтобы margin снизу задать. Сделай просто 
.input-form__container - ему задаешь margin снизу
.input-form__container:last-child - ему ставишь нулевый margin

2022-02-01 22:13 UTC, Muslik commented on blocks/ui-kit.html
> +            <button class="input-form__button">
Тут это просто иконка. Кнопка не нужна

2022-02-02 10:18 UTC, merged